"""SEQ-001 seven-message outreach sequence

Revision ID: 0926b59b7912
Revises: c1f7a3e29b04
Create Date: 2026-08-06 19:58:51.625367

Four new tables and ten new enum types. Nothing existing is altered: no column
is added to ``draft_versions``, no constraint on it is relaxed, no historical
draft is read or rewritten, and no approval changes meaning. A database that
never enables the ``email_sequences`` feature flag behaves exactly as it did
before this revision ran.

## What each table is for

``email_sequence_messages`` -- seven rows per sequence carrying *identity*
only: position, type, purpose, predecessor, and a future delivery state. No
text. This is the row a later Gmail adapter would attach a thread to, which is
why it has to survive both regeneration and editing.

``email_sequences`` -- one row per generation, immutable. The digest, producer,
policy, strategy, context decision and lineage that the whole sequence rests
on.

``email_sequence_message_versions`` -- one row per immutable content version of
one message. Editing message 3 writes one row and supersedes one row.

``email_sequence_message_reviews`` -- one decision per exact message version.

## The three constraints that carry the safety properties

``uq_email_sequences_current_membership`` is a *partial* unique index on
``campaign_contact_id where superseded_at is null``. It is what makes "one live
sequence per Campaign Contact" a database fact rather than an application
convention, while leaving every superseded row in place for audit.

``uq_email_sequence_message_versions_current`` does the same job one level
down: exactly one live version per logical message, history retained.

``ck_email_sequence_messages_initial_is_first_and_unchained`` enforces both
halves of the chain rule in one expression -- position 1 is the initial message
and has no predecessor, every other position is a follow-up and names one.
Split into two constraints it would admit a chain that starts twice, or one
that never starts.

``uq_email_sequence_messages_sequence_key_purpose`` is the reason two positions
cannot claim the same purpose. A sequence whose messages share a purpose has
not been planned as a sequence, and that is a schema-level fact here rather
than a validator that could be bypassed.

## Why this sits on top of IMP-001 rather than on ``b6d4e07a1f38``

This revision and IMP-001's ``c1f7a3e29b04`` were authored in parallel, and each
was written with ``down_revision = "b6d4e07a1f38"``. Left that way they are two
Alembic heads, which ``alembic upgrade head`` refuses to resolve and which the
migration-chain test rejects outright.

The repair is a re-parent, not an ``alembic merge``. A merge revision would
give one revision two parents, and
``test_the_assembled_migration_chain_has_exactly_one_head`` asserts that no
revision in this project has more than one down-revision. Re-parenting keeps the
graph a straight line: ``b6d4e07a1f38 -> c1f7a3e29b04 -> 0926b59b7912``.

Ordering is safe in either direction because the two revisions share no schema
object. IMP-001 creates ``imported_contact_emails`` and
``import_source_identifiers`` and adds columns to ``import_batches`` and
``import_row_validations``; this revision creates four ``email_sequence*``
tables and alters nothing that already exists. The name prefixes are disjoint,
so nothing collides whichever runs first. Sequencing it after IMP-001 is
therefore a bookkeeping choice, and the honest one: the import work landed on
``main`` first.

## Reversibility

``downgrade`` refuses outright while any of the four tables holds a row -- see
the function docstring for why generated copy and human review decisions are
treated as unrecoverable. On an empty schema it drops the four tables and then
the ten enum types it created.
Dropping a table does not drop the types it used, so without the explicit
``DROP TYPE`` a downgrade followed by a re-upgrade would fail on
``CREATE TYPE ... already exists``. ``IF EXISTS`` keeps the downgrade safe to
re-run. No data outside these four tables is touched in either direction, so a
downgrade loses generated sequences and nothing else.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0926b59b7912"
down_revision: str | Sequence[str] | None = "c1f7a3e29b04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_sequence_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sequence_key", sa.UUID(), nullable=False),
        sa.Column("campaign_contact_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("INITIAL", "FOLLOW_UP", name="sequence_message_type"),
            nullable=False,
        ),
        sa.Column(
            "purpose",
            sa.Enum(
                "INITIAL_OUTREACH",
                "CONCISE_REMINDER",
                "NEW_ANGLE",
                "ROLE_RELEVANCE",
                "PROOF_OR_OUTCOME",
                "LOW_FRICTION_RESOURCE",
                "CLOSE_THE_LOOP",
                name="sequence_message_purpose",
            ),
            nullable=False,
        ),
        sa.Column("predecessor_message_id", sa.UUID(), nullable=True),
        sa.Column(
            "delivery_state",
            sa.Enum(
                "NOT_READY",
                "WAITING_FOR_PREDECESSOR",
                "WAITING_FOR_DUE_DATE",
                "ELIGIBLE_FOR_DRAFT",
                "EXTERNAL_DRAFT_CREATED",
                "WAITING_FOR_MANUAL_SEND",
                "SENT_DETECTED",
                "HELD",
                "STOPPED",
                "SYNC_FAILED",
                name="sequence_delivery_state",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(position = 1 AND message_type = 'INITIAL' AND predecessor_message_id IS NULL)"
            " OR (position > 1 AND message_type = 'FOLLOW_UP'"
            " AND predecessor_message_id IS NOT NULL)",
            name=op.f("ck_email_sequence_messages_initial_is_first_and_unchained"),
        ),
        sa.CheckConstraint(
            "position >= 1 AND position <= 7",
            name=op.f("ck_email_sequence_messages_position_within_sequence"),
        ),
        sa.CheckConstraint(
            "predecessor_message_id IS NULL OR predecessor_message_id <> id",
            name=op.f("ck_email_sequence_messages_predecessor_is_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_contact_id"],
            ["campaign_contacts.id"],
            name=op.f("fk_email_sequence_messages_campaign_contact_id_campaign_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_message_id"],
            ["email_sequence_messages.id"],
            name=op.f("fk_email_sequence_messages_predecessor_message_id_email_sequence_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_sequence_messages")),
        sa.UniqueConstraint(
            "sequence_key", "position", name="uq_email_sequence_messages_sequence_key"
        ),
        sa.UniqueConstraint(
            "sequence_key", "purpose", name="uq_email_sequence_messages_sequence_key_purpose"
        ),
    )
    op.create_index(
        "ix_email_sequence_messages_campaign_contact_id",
        "email_sequence_messages",
        ["campaign_contact_id"],
        unique=False,
    )
    op.create_table(
        "email_sequences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sequence_key", sa.UUID(), nullable=False),
        sa.Column("sequence_version", sa.Integer(), nullable=False),
        sa.Column("campaign_contact_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("agent_job_id", sa.UUID(), nullable=True),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("producer", sa.String(length=128), nullable=True),
        sa.Column("producer_version", sa.String(length=64), nullable=True),
        sa.Column("sequence_producer_version", sa.String(length=64), nullable=False),
        sa.Column("validation_policy_version", sa.String(length=64), nullable=False),
        sa.Column("personalization_policy_version_id", sa.UUID(), nullable=True),
        sa.Column("personalization_policy_version_number", sa.Integer(), nullable=True),
        sa.Column("personalization_strategy_id", sa.String(length=64), nullable=True),
        sa.Column(
            "personalization_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("research_lineage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("insights_lineage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("intelligence_lineage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cadence_source", sa.String(length=32), nullable=False),
        sa.Column("planned_span_days", sa.Integer(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column(
            "generation_status",
            sa.Enum("COMPLETE", "PARTIAL", "FAILED", name="sequence_generation_status"),
            nullable=False,
        ),
        sa.Column(
            "validation_status",
            sa.Enum("PASSED", "PASSED_WITH_WARNINGS", "FAILED", name="sequence_validation_status"),
            nullable=False,
        ),
        sa.Column(
            "review_state",
            sa.Enum(
                "GENERATED",
                "NEEDS_REVIEW",
                "PARTIALLY_REVIEWED",
                "PARTIALLY_APPROVED",
                "APPROVED",
                "CONTAINS_EDITS",
                "CONTAINS_DISCARDED",
                "BLOCKED",
                "FAILED",
                "SUPERSEDED",
                name="sequence_review_state",
            ),
            nullable=False,
        ),
        sa.Column("validation_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "stop_state", sa.Enum("RUNNING", "STOPPED", name="sequence_stop_state"), nullable=False
        ),
        sa.Column(
            "stop_reason",
            sa.Enum(
                "RECIPIENT_REPLY_DETECTED",
                "OPERATOR_HOLD",
                "OPERATOR_CANCELLED",
                "MAILBOX_DISCONNECTED",
                "CONTACT_SUPPRESSED",
                "CAMPAIGN_PAUSED",
                "CAMPAIGN_ARCHIVED",
                "CONTACT_REMOVED_FROM_CAMPAIGN",
                "SYNCHRONIZATION_FAILURE",
                name="sequence_stop_reason",
            ),
            nullable=True,
        ),
        sa.Column("current_actionable_position", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(stop_state = 'RUNNING' AND stop_reason IS NULL)"
            " OR (stop_state = 'STOPPED' AND stop_reason IS NOT NULL)",
            name=op.f("ck_email_sequences_stop_reason_paired_with_stop_state"),
        ),
        sa.CheckConstraint(
            "btrim(input_digest) <> ''", name=op.f("ck_email_sequences_input_digest_not_blank")
        ),
        sa.CheckConstraint(
            "current_actionable_position IS NULL"
            " OR (current_actionable_position >= 1 AND current_actionable_position <= 7)",
            name=op.f("ck_email_sequences_actionable_position_within_sequence"),
        ),
        sa.CheckConstraint(
            "message_count >= 0 AND message_count <= 7",
            name=op.f("ck_email_sequences_message_count_within_sequence"),
        ),
        sa.CheckConstraint(
            "sequence_version > 0", name=op.f("ck_email_sequences_sequence_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["agent_job_id"],
            ["verification_jobs.id"],
            name=op.f("fk_email_sequences_agent_job_id_verification_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_contact_id"],
            ["campaign_contacts.id"],
            name=op.f("fk_email_sequences_campaign_contact_id_campaign_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_email_sequences_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_email_sequences_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_email_sequences_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["personalization_policy_version_id"],
            ["personalization_policy_versions.id"],
            name=op.f(
                "fk_email_sequences_personalization_policy_version_id_personalization_policy_versions"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["email_sequences.id"],
            name=op.f("fk_email_sequences_superseded_by_id_email_sequences"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_sequences")),
        sa.UniqueConstraint(
            "sequence_key", "sequence_version", name="uq_email_sequences_sequence_key"
        ),
    )
    op.create_index(
        "ix_email_sequences_campaign_id", "email_sequences", ["campaign_id"], unique=False
    )
    op.create_index(
        "ix_email_sequences_contact_id", "email_sequences", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_email_sequences_digest",
        "email_sequences",
        ["campaign_contact_id", "input_digest"],
        unique=False,
    )
    op.create_index(
        "uq_email_sequences_current_membership",
        "email_sequences",
        ["campaign_contact_id"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_table(
        "email_sequence_message_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("sequence_id", sa.UUID(), nullable=False),
        sa.Column("message_version", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("recommended_delay_days", sa.Integer(), nullable=False),
        sa.Column("recommended_elapsed_day", sa.Integer(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("GENERATED", "HUMAN_EDITED", "REGENERATED", name="sequence_message_origin"),
            nullable=False,
        ),
        sa.Column(
            "generation_status",
            sa.Enum("COMPLETE", "PARTIAL", "FAILED", name="sequence_generation_status"),
            nullable=False,
        ),
        sa.Column(
            "validation_status",
            sa.Enum("PASSED", "PASSED_WITH_WARNINGS", "FAILED", name="sequence_validation_status"),
            nullable=False,
        ),
        sa.Column("personalization_policy_version_id", sa.UUID(), nullable=True),
        sa.Column("personalization_strategy_id", sa.String(length=64), nullable=True),
        sa.Column("context_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence_insight_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("intelligence_accepted_count", sa.Integer(), nullable=False),
        sa.Column("intelligence_excluded_count", sa.Integer(), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column("original_subject", sa.Text(), nullable=True),
        sa.Column("original_body", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "btrim(body) <> ''", name=op.f("ck_email_sequence_message_versions_body_not_blank")
        ),
        sa.CheckConstraint(
            "btrim(subject) <> ''",
            name=op.f("ck_email_sequence_message_versions_subject_not_blank"),
        ),
        sa.CheckConstraint(
            "origin <> 'HUMAN_EDITED'"
            " OR (original_subject IS NOT NULL AND original_body IS NOT NULL"
            " AND source_version_id IS NOT NULL)",
            name=op.f("ck_email_sequence_message_versions_human_edit_keeps_its_source"),
        ),
        sa.CheckConstraint(
            "(position = 1 AND recommended_delay_days = 0"
            " AND recommended_elapsed_day = 0) OR position > 1",
            name=op.f("ck_email_sequence_message_versions_initial_starts_at_day_zero"),
        ),
        sa.CheckConstraint(
            "message_version > 0",
            name=op.f("ck_email_sequence_message_versions_message_version_positive"),
        ),
        sa.CheckConstraint(
            "position >= 1 AND position <= 7",
            name=op.f("ck_email_sequence_message_versions_position_within_sequence"),
        ),
        sa.CheckConstraint(
            "recommended_delay_days >= 0 AND recommended_delay_days <= 365",
            name=op.f("ck_email_sequence_message_versions_delay_within_bounds"),
        ),
        sa.CheckConstraint(
            "recommended_elapsed_day >= 0 AND recommended_elapsed_day <= 3650",
            name=op.f("ck_email_sequence_message_versions_elapsed_day_within_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_sequence_messages.id"],
            name=op.f("fk_email_sequence_message_versions_message_id_email_sequence_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["personalization_policy_version_id"],
            ["personalization_policy_versions.id"],
            name=op.f(
                "fk_email_sequence_message_versions_personalization_policy_version_id_personalization_policy_versions"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["email_sequences.id"],
            name=op.f("fk_email_sequence_message_versions_sequence_id_email_sequences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["email_sequence_message_versions.id"],
            name=op.f(
                "fk_email_sequence_message_versions_source_version_id_email_sequence_message_versions"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_sequence_message_versions")),
        sa.UniqueConstraint(
            "message_id", "message_version", name="uq_email_sequence_message_versions_message_id"
        ),
    )
    op.create_index(
        "ix_email_sequence_message_versions_message_id",
        "email_sequence_message_versions",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        "ix_email_sequence_message_versions_sequence_id",
        "email_sequence_message_versions",
        ["sequence_id"],
        unique=False,
    )
    op.create_index(
        "uq_email_sequence_message_versions_current",
        "email_sequence_message_versions",
        ["message_id"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_table(
        "email_sequence_message_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_version_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("APPROVED", "DISCARDED", "INVALIDATED", name="sequence_review_decision"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("bulk_operation_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "btrim(decided_by) <> ''",
            name=op.f("ck_email_sequence_message_reviews_decided_by_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_sequence_messages.id"],
            name=op.f("fk_email_sequence_message_reviews_message_id_email_sequence_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_version_id"],
            ["email_sequence_message_versions.id"],
            name=op.f(
                "fk_email_sequence_message_reviews_message_version_id_email_sequence_message_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_sequence_message_reviews")),
        sa.UniqueConstraint(
            "message_version_id", name="uq_email_sequence_message_reviews_message_version_id"
        ),
    )
    op.create_index(
        "ix_email_sequence_message_reviews_bulk",
        "email_sequence_message_reviews",
        ["bulk_operation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse cleanly on an empty schema; refuse once there is data to lose.

    Two of the four tables hold records that exist nowhere else in the database
    and cannot be re-derived by anything. The generated message versions are the
    only copy of the copy -- regenerating produces different text, because the
    inputs, the policy and the producer have all moved on. The review rows are
    the only record of *what a human decided*, and no automatic reconstruction
    of an approval is honest: a rebuilt approval is a guess about somebody's
    judgement, not the judgement they made.

    So this follows the convention APP-003 (``c48b1f70a3d2``) established here
    and KB-001, CI-001 and DAT-017A also follow. The refusal is conditional on
    there being something to protect: a database that has never generated a
    sequence reverses without ceremony -- which is what keeps the round-trip
    migration test meaningful -- and one that has stops and says what to do
    instead.

    The message says how much would be lost and of what kind. It deliberately
    does not name a row, quote a subject or expose a schema detail: an operator
    needs to know the scale of what they are about to destroy, not to receive a
    sample of the content through an error string.
    """

    bind = op.get_bind()
    populated: list[str] = []
    for table, label in (
        ("email_sequence_message_reviews", "recorded human review decision(s)"),
        ("email_sequence_message_versions", "generated or edited message version(s)"),
        ("email_sequences", "generated sequence(s)"),
        ("email_sequence_messages", "sequence message identity record(s)"),
    ):
        # `to_regclass` returns NULL rather than raising when the table is
        # absent, so a partially-applied schema reports "nothing to lose"
        # instead of failing with a confusing undefined-table error.
        exists = bind.execute(
            sa.text("SELECT to_regclass(:name)"), {"name": f"public.{table}"}
        ).scalar()
        if exists is None:
            continue
        count = bind.execute(sa.text(f"SELECT count(*) FROM {table}")).scalar_one()
        if count:
            populated.append(f"{count} {label}")

    if populated:
        raise RuntimeError(
            "SEQ-001 (0926b59b7912) will not downgrade while the seven-message sequence "
            "tables hold data that exists nowhere else: "
            + ", ".join(populated)
            + ". Reversing would destroy generated copy and recorded human approval "
            "decisions silently, and neither can be re-derived — regenerating produces "
            "different text, and a rebuilt approval is a guess about somebody's judgement "
            "rather than the judgement they made. Restore from a backup taken before the "
            "upgrade instead, or delete the sequence data deliberately first if it is "
            "genuinely disposable."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_email_sequence_message_reviews_bulk", table_name="email_sequence_message_reviews"
    )
    op.drop_table("email_sequence_message_reviews")
    op.drop_index(
        "uq_email_sequence_message_versions_current",
        table_name="email_sequence_message_versions",
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index(
        "ix_email_sequence_message_versions_sequence_id",
        table_name="email_sequence_message_versions",
    )
    op.drop_index(
        "ix_email_sequence_message_versions_message_id",
        table_name="email_sequence_message_versions",
    )
    op.drop_table("email_sequence_message_versions")
    op.drop_index(
        "uq_email_sequences_current_membership",
        table_name="email_sequences",
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index("ix_email_sequences_digest", table_name="email_sequences")
    op.drop_index("ix_email_sequences_contact_id", table_name="email_sequences")
    op.drop_index("ix_email_sequences_campaign_id", table_name="email_sequences")
    op.drop_table("email_sequences")
    op.drop_index(
        "ix_email_sequence_messages_campaign_contact_id", table_name="email_sequence_messages"
    )
    op.drop_table("email_sequence_messages")
    # Dropping a table leaves the enum types it used behind, and a later
    # re-upgrade would then fail on "type already exists". Order is irrelevant
    # here -- no type is referenced by anything once the four tables are gone.
    for _type_name in (
        "sequence_review_decision",
        "sequence_message_origin",
        "sequence_stop_reason",
        "sequence_stop_state",
        "sequence_review_state",
        "sequence_validation_status",
        "sequence_generation_status",
        "sequence_delivery_state",
        "sequence_message_purpose",
        "sequence_message_type",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {_type_name}"))
    # ### end Alembic commands ###
