"""phase 2 email verification: candidates, jobs, usage, evidence fields

Revision ID: 93c46f2a8df9
Revises: 2ea0cc07b430
Create Date: 2026-07-24 04:36:08.986157

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93c46f2a8df9"
down_revision: str | Sequence[str] | None = "2ea0cc07b430"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Native ENUM types introduced by this revision (dropped on downgrade so a
# re-upgrade can recreate them cleanly — matches the DAT-001 convention).
NEW_ENUM_TYPES = (
    "email_candidate_source",
    "verification_job_status",
    "verification_usage_event_type",
)

# Partial-index predicate for the single-active-job-per-address invariant. Uses
# enum-typed literals so the expression is IMMUTABLE (required for the predicate).
_ACTIVE_JOB_PREDICATE = (
    "status IN ("
    "'PENDING'::verification_job_status,"
    "'IN_PROGRESS'::verification_job_status,"
    "'RETRY_SCHEDULED'::verification_job_status)"
)


def upgrade() -> None:
    """Upgrade schema."""
    # Extend the existing address-result enum with the DISPOSABLE outcome.
    # Autogenerate cannot detect enum-value additions, so it is explicit here.
    # ADD VALUE is additive and safe; the value is never used in this same
    # transaction. On a full downgrade-to-base the whole type is dropped by the
    # DAT-001 revision, so this addition round-trips without a manual removal
    # (PostgreSQL cannot drop a single enum value without recreating the type).
    op.execute("ALTER TYPE email_verification_result ADD VALUE IF NOT EXISTS 'DISPOSABLE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "source",
            sa.Enum("IMPORTED", "GENERATED", name="email_candidate_source"),
            nullable=False,
        ),
        sa.Column("pattern", sa.String(length=255), nullable=True),
        sa.Column("local_part", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("engine_version", sa.String(length=50), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("rank_score", sa.Float(), nullable=False),
        sa.Column("rank_reason", sa.Text(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("selection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_email_candidates_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_candidates")),
        sa.UniqueConstraint("contact_id", "email", name="uq_email_candidates_contact_email"),
    )
    op.create_index(
        "ix_email_candidates_contact_id", "email_candidates", ["contact_id"], unique=False
    )
    op.create_index("ix_email_candidates_email", "email_candidates", ["email"], unique=False)
    op.create_index(
        "uq_email_candidates_one_selected",
        "email_candidates",
        ["contact_id"],
        unique=True,
        postgresql_where="selected",
    )
    op.create_table(
        "verification_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=400), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "RETRY_SCHEDULED",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="verification_job_status",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=100), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("outcome_status", sa.String(length=50), nullable=True),
        sa.Column("verification_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_verification_jobs_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["exact_email_verifications.id"],
            name=op.f("fk_verification_jobs_verification_id_exact_email_verifications"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_verification_jobs_idempotency_key"),
    )
    op.create_index(
        "ix_verification_jobs_claimable",
        "verification_jobs",
        ["status", "next_run_at"],
        unique=False,
    )
    op.create_index(
        "ix_verification_jobs_contact_id", "verification_jobs", ["contact_id"], unique=False
    )
    op.create_index("ix_verification_jobs_email", "verification_jobs", ["email"], unique=False)
    op.create_index(
        "uq_verification_jobs_active_email",
        "verification_jobs",
        ["email"],
        unique=True,
        postgresql_where=_ACTIVE_JOB_PREDICATE,
    )
    op.create_table(
        "verification_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CALL_MADE",
                "CACHE_REUSE",
                "PROVIDER_ERROR",
                "TIMEOUT",
                "INSUFFICIENT_CREDITS",
                "RETRY_SCHEDULED",
                "STALE_DETECTED",
                "CONFLICT_DETECTED",
                "RECOVERED",
                name="verification_usage_event_type",
            ),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=True),
        sa.Column("credited", sa.Boolean(), nullable=False),
        sa.Column("credits_remaining", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_verification_usage_events_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["verification_jobs.id"],
            name=op.f("fk_verification_usage_events_job_id_verification_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_usage_events")),
    )
    op.create_index(
        "ix_verification_usage_events_created_at",
        "verification_usage_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_verification_usage_events_email", "verification_usage_events", ["email"], unique=False
    )
    op.create_index(
        "ix_verification_usage_events_type",
        "verification_usage_events",
        ["event_type"],
        unique=False,
    )
    op.add_column(
        "exact_email_verifications", sa.Column("subresult", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "exact_email_verifications", sa.Column("quality", sa.String(length=50), nullable=True)
    )
    op.add_column("exact_email_verifications", sa.Column("is_role", sa.Boolean(), nullable=True))
    op.add_column("exact_email_verifications", sa.Column("is_free", sa.Boolean(), nullable=True))
    op.add_column(
        "exact_email_verifications", sa.Column("did_you_mean", sa.String(length=320), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exact_email_verifications", "did_you_mean")
    op.drop_column("exact_email_verifications", "is_free")
    op.drop_column("exact_email_verifications", "is_role")
    op.drop_column("exact_email_verifications", "quality")
    op.drop_column("exact_email_verifications", "subresult")
    op.drop_index("ix_verification_usage_events_type", table_name="verification_usage_events")
    op.drop_index("ix_verification_usage_events_email", table_name="verification_usage_events")
    op.drop_index("ix_verification_usage_events_created_at", table_name="verification_usage_events")
    op.drop_table("verification_usage_events")
    op.drop_index(
        "uq_verification_jobs_active_email",
        table_name="verification_jobs",
        postgresql_where=_ACTIVE_JOB_PREDICATE,
    )
    op.drop_index("ix_verification_jobs_email", table_name="verification_jobs")
    op.drop_index("ix_verification_jobs_contact_id", table_name="verification_jobs")
    op.drop_index("ix_verification_jobs_claimable", table_name="verification_jobs")
    op.drop_table("verification_jobs")
    op.drop_index(
        "uq_email_candidates_one_selected",
        table_name="email_candidates",
        postgresql_where="selected",
    )
    op.drop_index("ix_email_candidates_email", table_name="email_candidates")
    op.drop_index("ix_email_candidates_contact_id", table_name="email_candidates")
    op.drop_table("email_candidates")

    # Drop the ENUM types this revision introduced so a re-upgrade recreates them.
    # The DISPOSABLE value added to email_verification_result is intentionally not
    # removed: PostgreSQL cannot drop a single enum value, and the value is
    # harmless (the whole type is dropped by DAT-001 on a downgrade to base).
    bind = op.get_bind()
    for enum_name in NEW_ENUM_TYPES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
