"""provider-neutral usage ledger + verification job campaign

Revision ID: ad1e298fb49a
Revises: 93c46f2a8df9
Create Date: 2026-07-24 05:07:57.979913

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad1e298fb49a"
down_revision: str | Sequence[str] | None = "93c46f2a8df9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("job_kind", sa.String(length=50), nullable=True),
        sa.Column("request_ref", sa.String(length=255), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=True),
        sa.Column(
            "cache_status",
            sa.Enum("HIT", "MISS", "NOT_APPLICABLE", name="usage_cache_status"),
            nullable=False,
        ),
        sa.Column("retry_number", sa.Integer(), nullable=False),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("provider_cost", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "charge_status",
            sa.Enum("CONFIRMED", "UNCERTAIN", "NONE", name="usage_charge_status"),
            nullable=False,
        ),
        sa.Column("credits_remaining", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_usage_ledger_entries_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_usage_ledger_entries_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_ledger_entries")),
    )
    op.create_index(
        "ix_usage_ledger_entries_campaign_id", "usage_ledger_entries", ["campaign_id"], unique=False
    )
    op.create_index(
        "ix_usage_ledger_entries_job", "usage_ledger_entries", ["job_kind", "job_id"], unique=False
    )
    op.create_index(
        "ix_usage_ledger_entries_provider", "usage_ledger_entries", ["provider"], unique=False
    )
    op.create_index(
        "ix_usage_ledger_entries_provider_attempted",
        "usage_ledger_entries",
        ["provider", "attempted_at"],
        unique=False,
    )
    op.add_column("verification_jobs", sa.Column("campaign_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_verification_jobs_campaign_id_campaigns"),
        "verification_jobs",
        "campaigns",
        ["campaign_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_verification_jobs_campaign_id_campaigns"), "verification_jobs", type_="foreignkey"
    )
    op.drop_column("verification_jobs", "campaign_id")
    op.drop_index("ix_usage_ledger_entries_provider_attempted", table_name="usage_ledger_entries")
    op.drop_index("ix_usage_ledger_entries_provider", table_name="usage_ledger_entries")
    op.drop_index("ix_usage_ledger_entries_job", table_name="usage_ledger_entries")
    op.drop_index("ix_usage_ledger_entries_campaign_id", table_name="usage_ledger_entries")
    op.drop_table("usage_ledger_entries")

    # Drop the ENUM types this revision introduced so a re-upgrade recreates them.
    bind = op.get_bind()
    for enum_name in ("usage_cache_status", "usage_charge_status"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
