"""dat 001 core schema completion

Revision ID: b84699f38ef5
Revises: c11379ba2041
Create Date: 2026-07-23 14:24:01.438959

Completes the Phase 1 (DAT-001) core schema: companies; three structurally
distinct email-evidence tables (exact-address verifications, domain-pattern
observations, mail-domain observations); research insights and evidence
references; versioned scores, components, and score-evidence links; immutable
draft versions and exact-version approvals; external-provider events with
duplicate protection. Also extends the import schema with CSV/XLSX format
metadata (source format, MIME type, parser/mapper version, per-sheet identity).

This slice is database representation only — no later-phase behaviour (no
MillionVerifier, scoring, research, drafting, approvals UI, or Saleshandy).

The downgrade drops the new PostgreSQL ENUM types as well as the tables so an
upgrade -> downgrade -> upgrade round trip succeeds cleanly (exercised in CI).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b84699f38ef5"
down_revision: str | Sequence[str] | None = "c11379ba2041"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ENUM types introduced by this revision (auto-created on upgrade; PostgreSQL
# does not drop them on drop_table/drop_column, so they are dropped explicitly
# on downgrade).
ENUM_TYPES: tuple[str, ...] = (
    "import_source_format",
    "email_verification_result",
    "insight_subject",
    "score_type",
    "approval_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("industry", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("company_size", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index("ix_companies_name", "companies", ["name"], unique=False)
    op.create_index(
        "uq_companies_domain",
        "companies",
        ["domain"],
        unique=True,
        postgresql_where="domain IS NOT NULL",
    )
    op.create_table(
        "domain_pattern_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("sample_email", sa.String(length=320), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_pattern_observations")),
    )
    op.create_index(
        "ix_domain_pattern_observations_domain",
        "domain_pattern_observations",
        ["domain"],
        unique=False,
    )
    op.create_table(
        "external_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_events")),
        sa.UniqueConstraint(
            "provider", "external_event_id", name="uq_external_events_provider_event_id"
        ),
    )
    op.create_index(
        "ix_external_events_provider_type",
        "external_events",
        ["provider", "event_type"],
        unique=False,
    )
    op.create_index(
        "ix_external_events_received_at", "external_events", ["received_at"], unique=False
    )
    op.create_table(
        "mail_domain_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("is_catch_all", sa.Boolean(), nullable=True),
        sa.Column("accepts_all", sa.Boolean(), nullable=True),
        sa.Column("mx_provider", sa.String(length=255), nullable=True),
        sa.Column("raw_observation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mail_domain_observations")),
    )
    op.create_index(
        "ix_mail_domain_observations_domain", "mail_domain_observations", ["domain"], unique=False
    )
    op.create_table(
        "draft_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_draft_versions_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_draft_versions_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_versions")),
        sa.UniqueConstraint(
            "contact_id",
            "campaign_id",
            "version_number",
            name="uq_draft_versions_contact_campaign_version",
        ),
    )
    op.create_index(
        "ix_draft_versions_campaign_id", "draft_versions", ["campaign_id"], unique=False
    )
    op.create_index("ix_draft_versions_contact_id", "draft_versions", ["contact_id"], unique=False)
    op.create_table(
        "exact_email_verifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "result",
            sa.Enum("VALID", "INVALID", "CATCH_ALL", "UNKNOWN", name="email_verification_result"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_result_code", sa.String(length=100), nullable=True),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_exact_email_verifications_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exact_email_verifications")),
    )
    op.create_index(
        "ix_exact_email_verifications_checked_at",
        "exact_email_verifications",
        ["checked_at"],
        unique=False,
    )
    op.create_index(
        "ix_exact_email_verifications_email", "exact_email_verifications", ["email"], unique=False
    )
    op.create_table(
        "insights",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.Enum("COMPANY", "CONTACT", name="insight_subject"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_summary", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("freshness_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_insights_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_insights_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
    )
    op.create_index("ix_insights_company_id", "insights", ["company_id"], unique=False)
    op.create_index("ix_insights_contact_id", "insights", ["contact_id"], unique=False)
    op.create_index("ix_insights_subject", "insights", ["subject"], unique=False)
    op.create_table(
        "scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column(
            "score_type",
            sa.Enum("INITIAL_FIT", "OUTREACH_READINESS", name="score_type"),
            nullable=False,
        ),
        sa.Column("rule_version", sa.Text(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_scores_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_scores_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
    )
    op.create_index("ix_scores_campaign_id", "scores", ["campaign_id"], unique=False)
    op.create_index("ix_scores_contact_id", "scores", ["contact_id"], unique=False)
    op.create_index("ix_scores_type", "scores", ["score_type"], unique=False)
    op.create_table(
        "draft_approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("draft_version_id", sa.UUID(), nullable=False),
        sa.Column("approved_by", sa.Text(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.Enum("APPROVED", "INVALIDATED", name="approval_status"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["draft_version_id"],
            ["draft_versions.id"],
            name=op.f("fk_draft_approvals_draft_version_id_draft_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_approvals")),
        sa.UniqueConstraint("draft_version_id", name="uq_draft_approvals_draft_version"),
    )
    op.create_index(
        "ix_draft_approvals_draft_version_id", "draft_approvals", ["draft_version_id"], unique=False
    )
    op.create_table(
        "insight_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("insight_id", sa.UUID(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name=op.f("fk_insight_evidence_insight_id_insights"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_evidence")),
    )
    op.create_index(
        "ix_insight_evidence_insight_id", "insight_evidence", ["insight_id"], unique=False
    )
    op.create_table(
        "score_components",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("score_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["scores.id"],
            name=op.f("fk_score_components_score_id_scores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_components")),
        sa.UniqueConstraint("score_id", "name", name="uq_score_components_score_name"),
    )
    op.create_index("ix_score_components_score_id", "score_components", ["score_id"], unique=False)
    op.create_table(
        "score_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("score_id", sa.UUID(), nullable=False),
        sa.Column("insight_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name=op.f("fk_score_evidence_insight_id_insights"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["score_id"],
            ["scores.id"],
            name=op.f("fk_score_evidence_score_id_scores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_evidence")),
        sa.UniqueConstraint("score_id", "insight_id", name="uq_score_evidence_score_insight"),
    )
    op.create_index("ix_score_evidence_score_id", "score_evidence", ["score_id"], unique=False)
    # This ENUM type is used only by add_column below; unlike create_table,
    # add_column does not auto-create the type on PostgreSQL, so create it first.
    import_source_format = postgresql.ENUM("CSV", "XLSX", name="import_source_format")
    import_source_format.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "import_batches",
        sa.Column(
            "source_format",
            postgresql.ENUM("CSV", "XLSX", name="import_source_format", create_type=False),
            server_default="CSV",
            nullable=False,
        ),
    )
    op.add_column("import_batches", sa.Column("mime_type", sa.String(length=255), nullable=True))
    op.add_column(
        "import_batches", sa.Column("parser_version", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "import_batches", sa.Column("mapper_version", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "import_rows", sa.Column("sheet_index", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("import_rows", sa.Column("sheet_name", sa.String(length=255), nullable=True))
    op.drop_constraint(op.f("uq_import_rows_batch_row"), "import_rows", type_="unique")
    op.create_unique_constraint(
        "uq_import_rows_batch_sheet_row", "import_rows", ["batch_id", "sheet_index", "row_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_import_rows_batch_sheet_row", "import_rows", type_="unique")
    op.create_unique_constraint(
        op.f("uq_import_rows_batch_row"),
        "import_rows",
        ["batch_id", "row_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("import_rows", "sheet_name")
    op.drop_column("import_rows", "sheet_index")
    op.drop_column("import_batches", "mapper_version")
    op.drop_column("import_batches", "parser_version")
    op.drop_column("import_batches", "mime_type")
    op.drop_column("import_batches", "source_format")
    op.drop_index("ix_score_evidence_score_id", table_name="score_evidence")
    op.drop_table("score_evidence")
    op.drop_index("ix_score_components_score_id", table_name="score_components")
    op.drop_table("score_components")
    op.drop_index("ix_insight_evidence_insight_id", table_name="insight_evidence")
    op.drop_table("insight_evidence")
    op.drop_index("ix_draft_approvals_draft_version_id", table_name="draft_approvals")
    op.drop_table("draft_approvals")
    op.drop_index("ix_scores_type", table_name="scores")
    op.drop_index("ix_scores_contact_id", table_name="scores")
    op.drop_index("ix_scores_campaign_id", table_name="scores")
    op.drop_table("scores")
    op.drop_index("ix_insights_subject", table_name="insights")
    op.drop_index("ix_insights_contact_id", table_name="insights")
    op.drop_index("ix_insights_company_id", table_name="insights")
    op.drop_table("insights")
    op.drop_index("ix_exact_email_verifications_email", table_name="exact_email_verifications")
    op.drop_index("ix_exact_email_verifications_checked_at", table_name="exact_email_verifications")
    op.drop_table("exact_email_verifications")
    op.drop_index("ix_draft_versions_contact_id", table_name="draft_versions")
    op.drop_index("ix_draft_versions_campaign_id", table_name="draft_versions")
    op.drop_table("draft_versions")
    op.drop_index("ix_mail_domain_observations_domain", table_name="mail_domain_observations")
    op.drop_table("mail_domain_observations")
    op.drop_index("ix_external_events_received_at", table_name="external_events")
    op.drop_index("ix_external_events_provider_type", table_name="external_events")
    op.drop_table("external_events")
    op.drop_index("ix_domain_pattern_observations_domain", table_name="domain_pattern_observations")
    op.drop_table("domain_pattern_observations")
    op.drop_index(
        "uq_companies_domain", table_name="companies", postgresql_where="domain IS NOT NULL"
    )
    op.drop_index("ix_companies_name", table_name="companies")
    op.drop_table("companies")

    # Drop the ENUM types this revision introduced so a re-upgrade can recreate them.
    bind = op.get_bind()
    for enum_name in ENUM_TYPES:
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
